spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/tosshelper?characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 1111

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        #        format_sql: true #To beautify or pretty print the SQL
        #        show_sql: true #show sql
        default_batch_fetch_size: 100

logging:
  level:
    org.hibernate.SQL: debug  #??????? ???? SQL ????
    org.hibernate.type: trace #?? ???? ?? ???


springdoc:
  swagger-ui:
    path: /swagger-ui.html
    groups-order: DESC
    tags-sorter: alpha
    operations-sorter: method
    disable-swagger-default-url: true
    display-request-duration: true
  api-docs:
    path: /api-docs
  show-actuator: true
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  paths-to-match:
    - /api/**